apiVersion: v1
kind: Pod
metadata:
  name: hans-test-result-app-pod
  labels:
    name: result-app-pod
    app: demo-voting-app
spec:
  containers:
  - name: result-app
    image: dockersamples/examplevotingapp_result
    ports:
      - containerPort: 80